env = SDL_VIDEODRIVER,wayland

input {
    touchpad {
        natural_scroll = true
    }
}

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct

exec-once = caelestia shell -d
exec-once = ~/.config/hypr/scripts/monitor-hotplug.sh

general {
    gaps_in = 2
    gaps_out = 5
}

bind = $mainMod, SHIFT_R,exec, ~/.config/hypr/scripts/launcher.sh
bind = $mainMod, G, exec, google-chrome-stable
bind = $mainMod SHIFT, S, exec, flameshot gui
bind = $mainMod, D, exec, vesktop
bind = $mainMod, Z, exec, zed
bind = $mainMod, L, exec, org.telegram.desktop

gesture = 3, horizontal, workspace
gesture = 3, swipe, mod: SUPER, move

# discord popout
windowrule = float on, move (1350) (41), size 530 321, pin on, border_size 0, match:initial_title (Discord Popout)

# monitor=eDP-1,preferred,1920x0,1
# monitor=HDMI-A-1,1920x1080@74.97Hz,0x0,1
