exec = hyprctl dispatch submap global
submap = global

# ## Shell keybinds
# Launcher
bindi = $mainMod, Super_L, global, caelestia:launcher
bindin = $mainMod, catchall, global, caelestia:launcherInterrupt
