env = SDL_VIDEODRIVER,wayland

input {
    touchpad {
        natural_scroll = true
    }
}

exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps
env = QT_QPA_PLATFORMTHEME,qt6ct

exec-once = caelestia shell -d
exec-once = ~/.config/hypr/scripts/setup-monitors.sh
exec-once = hypridle

general {
    gaps_in = 2
    gaps_out = 5
}

bind = $mainMod, SPACE,exec, ~/.config/hypr/scripts/launcher.sh
bind = $mainMod, G, exec, google-chrome-stable
bind = $mainMod SHIFT, S, exec, flameshot gui
bind = $mainMod, D, exec, discord
bind = $mainMod, Z, exec, zed
bind = $mainMod SHIFT, T, exec, Telegram
bind = $mainMod, L, exec, hyprlock
bind = $mainMod, S, exec, grim -g "$(slurp)" - | wl-copy
bind = $mainMod SHIFT, M, exec, ~/.config/hypr/scripts/setup_monitors.sh

gesture = 3, horizontal, workspace
gesture = 3, swipe, mod: SUPER, move

# discord popout
windowrule = float on, move (1350) (41), size 530 321, pin on, border_size 0, match:initial_title (Discord Popout)

windowrule = move (1373) (7), size 540 1066, match:initial_title (DevTools)

# monitor=eDP-1,preferred,1920x0,1
# monitor=HDMI-A-1,1920x1080@74.97Hz,0x0,1

# decoration {
#     active_opacity = 0.92
 #    inactive_opacity = 0.85
# 
 #    blur {
  #       enabled = true
   #      size = 8
  #       passes = 3
    #     noise = 0.02
     #    contrast = 0.9
 #        brightness = 0.8
      #   xray = false
       #  new_optimizations = on
#         ignore_opacity = false
#     }
# }

source = ~/.config/hypr/monitors.conf
# Keep media & video apps fully opaque
windowrule = opacity 1.0 override 1.0 override, match:class (^mpv$)
windowrule = opacity 1.0 override 1.0 override, match:class (^vlc$)
windowrule = opacity 1.0 override 1.0 override, match:class (^zoom$)


